import { PublicPage } from "@/components/PublicPage";
import { BookOpenCheck, Eye, HandHeart, SearchCheck } from "lucide-react";
import { ViewportReveal } from "@/components/ViewportReveal";
import { deploymentAssets } from "@/lib/deploymentAssets";
import { Link } from "wouter";

const commitments = [
  { icon: Eye, title: "Raise awareness", copy: "We make boycott information easier to understand by bringing together clear product records, visible sources, and plain-language context for people making everyday purchasing decisions." },
  { icon: SearchCheck, title: "Support informed action", copy: "AVOIDITnow helps individuals look beyond a label or a claim. Our tools point to reviewed records and alternatives so that consumer choices can be thoughtful, practical, and grounded in available evidence." },
  { icon: HandHeart, title: "Stand with affected communities", copy: "We believe economic choices matter. By helping people reduce support for companies and products associated with oppression, we seek to strengthen public solidarity with Muslim communities facing harm around the world." },
];

export default function About() {
  return <PublicPage eyebrow="About AVOIDITnow" title="Awareness can become a considered act of solidarity" summary="AVOIDITnow is an emerging NGO that equips people with accessible boycott information, source-linked product checks, and practical alternatives for more conscientious consumer choices.">
    <section className="grid items-center gap-7 lg:grid-cols-[minmax(0,.92fr)_minmax(0,1.08fr)] lg:gap-9">
      <ViewportReveal delay={90}><section className="border-l-4 border-[#137547] bg-white p-6 shadow-[0_8px_24px_rgba(20,33,23,.035)] sm:p-8"><p className="text-xs font-extrabold uppercase tracking-[.17em] text-[#137547]">Our purpose</p><h2 className="mt-3 text-2xl font-bold tracking-[-.04em] text-[#172119]">To help people understand the influence of collective consumer choices.</h2><p className="mt-5 text-base leading-8 text-[#566159]">AVOIDITnow exists to raise awareness of products and companies that are the subject of boycott campaigns around the globe. We aim to enlighten communities about how purchasing decisions can affect corporate profits, and how reducing economic support can be part of wider efforts to challenge oppression affecting Muslim countries and communities.</p><p className="mt-5 text-base leading-8 text-[#566159]">Our role is to make the starting point clearer: connect a product search to its published source, explain the limits of what we know, and surface practical alternatives where the available material provides them.</p></section></ViewportReveal>
      <ViewportReveal variant="scale" delay={150}><figure className="relative overflow-hidden rounded-2xl border border-black/10 bg-white shadow-[0_16px_36px_rgba(20,33,23,.10)]"><img src={deploymentAssets.aboutBanner} alt="AVOIDITnow banner: Know what you buy. Choose with conscience." width={2048} height={1152} loading="lazy" decoding="async" className="aspect-video w-full object-cover" /><Link href="/directory" aria-label="Check a product" title="Check a product" className="absolute left-[3%] top-[74%] h-[14%] w-[35%] cursor-pointer rounded-full focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#137547] focus-visible:ring-offset-2"><span className="sr-only">Check a product</span></Link></figure></ViewportReveal>
    </section>
    <section className="mt-10 grid gap-4 lg:grid-cols-3">{commitments.map(({ icon: Icon, title, copy }, index) => <ViewportReveal key={title} variant="scale" delay={160 + index * 90}><article className="rounded-2xl border border-black/10 bg-white p-6 shadow-[0_8px_24px_rgba(20,33,23,.035)]"><Icon className="size-5 text-[#137547]" /><h2 className="mt-5 text-xl font-bold tracking-[-.03em] text-[#172119]">{title}</h2><p className="mt-3 text-sm leading-7 text-[#59645b]">{copy}</p></article></ViewportReveal>)}</section>
    <ViewportReveal variant="scale" delay={120}><section className="mt-10 rounded-2xl bg-[#142119] p-7 text-white sm:p-9"><BookOpenCheck className="size-6 text-[#f2c7c5]" /><p className="mt-5 text-xs font-extrabold uppercase tracking-[.17em] text-[#d8ebe0]">How we work</p><h2 className="mt-3 max-w-2xl text-2xl font-bold tracking-[-.04em]">Research-led, transparent, and careful with claims.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-[#d9e3dc]">AVOIDITnow does not treat a missing result as an endorsement and does not present general information as a final moral or legal ruling. We show the source behind published records, note the date it was reviewed, and encourage people to read the underlying material before deciding how to act.</p></section></ViewportReveal>
  </PublicPage>;
}
