import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { PublicPage, QueryState } from "@/components/PublicPage";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, ExternalLink, Globe2, Search, Star } from "lucide-react";
import { useMemo, useState } from "react";

const regions = ["All regions", "Ireland", "United Kingdom", "Europe", "North America", "Middle East", "Global"];

export default function Alternatives() {
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("all");
  const [region, setRegion] = useState("All regions");
  const input = useMemo(() => ({ query: query.trim() || undefined, category, region: region === "All regions" ? undefined : region }), [query, category, region]);
  const result = trpc.platform.directory.alternatives.useQuery(input);
  const categories = Array.from(new Set((result.data ?? []).map(item => item.category)));
  const rating = trpc.platform.directory.rateAlternative.useMutation({ onSuccess: () => result.refetch() });
  return <PublicPage eyebrow="Regional alternatives" title="Find an alternative you can actually source" summary="Every listed alternative is labelled by region and review date. Availability and sourcing change, so use the linked source as a starting point—not as a guarantee of stock or an ethical certification.">
    <div className="grid gap-3 rounded-2xl border border-black/10 bg-white p-3 shadow-[0_10px_30px_rgba(20,33,23,.05)] md:grid-cols-[1fr_210px_210px]"><label className="flex items-center gap-3 rounded-xl bg-[#f3f6f1] px-4"><Search className="size-5 text-[#137547]" /><Input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search alternatives" className="h-11 border-0 bg-transparent p-0 text-[#172119] placeholder:text-[#728076] focus-visible:ring-0" /></label><Select value={category} onValueChange={setCategory}><SelectTrigger className="h-11 border-black/10 bg-white text-[#334137]"><SelectValue /></SelectTrigger><SelectContent>{["all", ...categories].map(value => <SelectItem key={value} value={value}>{value === "all" ? "All categories" : value}</SelectItem>)}</SelectContent></Select><Select value={region} onValueChange={setRegion}><SelectTrigger className="h-11 border-black/10 bg-white text-[#334137]"><Globe2 className="mr-2 size-4 text-[#137547]" /><SelectValue /></SelectTrigger><SelectContent>{regions.map(value => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div>
    <p className="mt-4 text-xs leading-5 text-[#667169]">Editorial review is required before a regional alternative appears here. A regional listing does not mean universal availability, boycott clearance, or ethical certification; open the dated source link and check local availability before you buy.</p>
    <QueryState loading={result.isLoading} error={result.error} empty={!result.data?.length} emptyTitle="No source-linked alternatives match these filters" emptyDescription="Alternatives are shown only after an administrator has recorded their availability context and review date." emptyActionLabel="Check a product" emptyActionHref="/directory"><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{result.data?.map(item => <article key={item.id} className="rounded-2xl border border-black/10 bg-white p-6 shadow-[0_7px_20px_rgba(20,33,23,.035)]"><div className="flex items-start justify-between gap-3"><Badge className="border border-[#137547]/20 bg-[#e9f3eb] text-[#137547]">{item.verificationStatus}</Badge><span className="text-xs font-semibold text-[#667169]">{item.priceTier} range</span></div><h2 className="mt-7 text-xl font-bold text-[#172119]">{item.name}</h2><p className="mt-2 text-sm leading-6 text-[#59645b]">{item.description}</p><p className="mt-5 flex items-center gap-2 text-xs font-bold text-[#137547]"><Globe2 className="size-4" />{item.region || "Region pending review"}</p>{item.availabilityNote && <p className="mt-4 rounded-xl bg-[#f3f6f1] p-3 text-xs leading-5 text-[#536057]">{item.availabilityNote}</p>}<div className="mt-5 flex flex-wrap items-center gap-3 text-xs text-[#667169]">{item.sourceReviewedAt && <span>Reviewed {new Date(item.sourceReviewedAt).toLocaleDateString()}</span>}{item.sourceUrl && <a href={item.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-bold text-[#137547] hover:text-[#0e633b]">Source <ExternalLink className="size-3" /></a>}</div><p className="mt-5 flex items-center gap-2 text-xs font-semibold text-[#137547]"><CheckCircle2 className="size-4" />{item.endorsementCount} earned endorsements</p><div className="mt-4 border-t border-black/8 pt-4"><p className="flex items-center gap-1 text-sm font-bold text-[#172119]"><Star className="size-4 fill-[#ce2d32] text-[#ce2d32]" />{item.ratingCount ? `${item.averageRating.toFixed(1)} / 5` : "No community rating yet"}</p><div className="mt-2 flex items-center gap-1">{[1, 2, 3, 4, 5].map(score => <button key={score} onClick={() => rating.mutate({ alternativeId: item.id, score })} disabled={rating.isPending} aria-label={`Rate ${item.name} ${score} out of 5`} className="rounded p-1 text-[#a0aaa1] transition hover:bg-[#fff1f0] hover:text-[#ce2d32] disabled:opacity-40"><Star className="size-3.5" /></button>)}</div></div></article>)}</div></QueryState>
  </PublicPage>;
}
