import { BackLink, PublicPage, QueryState } from "@/components/PublicPage";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { ArrowRight, ExternalLink } from "lucide-react";
import { Link, useRoute } from "wouter";
import { ViewportReveal } from "@/components/ViewportReveal";

export function News() {
  const result = trpc.platform.news.list.useQuery({});
  return <PublicPage eyebrow="Focused source-linked updates" title="Gaza, Sudan, and humanitarian briefings" summary="A daily, source-linked briefing on Gaza, Sudan, and related humanitarian conflicts. It is refreshed from approved publishers and is not a general newswire."><ViewportReveal delay={80}><div className="mb-7 rounded-2xl border-l-4 border-[#c62030] bg-[#fff7f7] px-5 py-4 text-sm leading-6 text-zinc-700">Updates are limited to relevant reporting from Al Jazeera, BBC News, Middle East Eye, and Middle East News Agency (MENA). Read the original report before sharing or acting on a claim.</div></ViewportReveal><ViewportReveal delay={160}><QueryState loading={result.isLoading} error={result.error} empty={!result.data?.length} emptyTitle="No focused source-linked updates published yet" emptyDescription="The daily refresh publishes only approved, relevant reporting with a named source and visible date." emptyActionLabel="Check a product" emptyActionHref="/directory"><div className="grid gap-4 lg:grid-cols-3">{result.data?.map((article, index) => <ViewportReveal key={article.id} className={index === 0 ? "lg:col-span-2" : undefined} variant="scale" delay={220 + index * 90}><Link href={`/news/${article.slug}`} className={`group block rounded-2xl border border-black/10 bg-white p-6 shadow-[0_14px_36px_rgba(10,46,28,.05)] transition hover:-translate-y-1 hover:border-emerald-800/35 ${index === 0 ? "lg:p-9" : ""}`}><div className="flex flex-wrap items-center justify-between gap-3"><Badge className="border border-emerald-900/15 bg-emerald-50 text-emerald-900">{article.category}</Badge>{article.publishedAt && <span className="text-xs text-zinc-500">{new Date(article.publishedAt).toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" })}</span>}</div><h2 className="mt-7 max-w-2xl font-display text-2xl font-semibold tracking-[-.04em] text-zinc-950">{article.title}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-zinc-600">{article.excerpt}</p><div className="mt-6 flex items-center justify-between gap-4"><span className="text-xs font-medium text-zinc-500">Source: {article.sourceName ?? "Publisher named in article"}</span><span className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-800 group-hover:text-[#c62030]">Read briefing <ArrowRight className="size-4" /></span></div></Link></ViewportReveal>)}</div></QueryState></ViewportReveal></PublicPage>;
}

export function ArticleDetail() {
  const [, params] = useRoute("/news/:slug");
  const result = trpc.platform.news.detail.useQuery({ slug: params?.slug ?? "" }, { enabled: Boolean(params?.slug) });
  const article = result.data;
  return <PublicPage eyebrow="Published briefing" title={article?.title ?? "Article"} summary={article?.excerpt ?? "Loading the article."}><BackLink href="/news" children="Back to updates" /><QueryState loading={result.isLoading} error={result.error} empty={!article}>{article && <article className="mx-auto max-w-3xl"><div className="flex flex-wrap items-center gap-3"><Badge className="border border-emerald-900/15 bg-emerald-50 text-emerald-900">{article.category}</Badge>{article.publishedAt && <span className="text-xs text-zinc-500">Published {new Date(article.publishedAt).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}</span>}</div><div className="mt-8 whitespace-pre-line text-base leading-8 text-zinc-700">{article.content}</div>{article.sourceUrl && <a href={article.sourceUrl} target="_blank" rel="noreferrer" className="mt-10 inline-flex items-center gap-2 rounded-xl border border-black/12 bg-white px-4 py-3 text-sm font-semibold text-emerald-900 shadow-sm hover:bg-emerald-50">Open the source: {article.sourceName ?? "Publisher report"}<ExternalLink className="size-4" /></a>}</article>}</QueryState></PublicPage>;
}
