import { useAuth } from "@/_core/hooks/useAuth";
import { PublicPage, QueryState } from "@/components/PublicPage";
import { Button } from "@/components/ui/button";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { Heart, MessageCircle, PencilLine } from "lucide-react";

export default function Profile() {
  const { user, loading } = useAuth();
  const result = trpc.platform.profile.useQuery(undefined, { enabled: Boolean(user) });
  if (!loading && !user) return <PublicPage eyebrow="Your account" title="Build your contribution trail" summary="Sign in to see your submitted questions, answers, and donation receipts in one private record."><Button onClick={() => startLogin()} className="bg-emerald-300 font-semibold text-emerald-950 hover:bg-emerald-200">Sign in with Manus</Button></PublicPage>;
  return <PublicPage eyebrow="Your account" title={user?.name ? `${user.name}'s contribution trail` : "Your contribution trail"} summary="A private record of what you have contributed to the shared resource."><QueryState loading={loading || result.isLoading} error={result.error} empty={false}><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/[.035] p-6"><MessageCircle className="size-5 text-emerald-300" /><p className="mt-5 text-3xl font-semibold text-white">{result.data?.questions.length ?? 0}</p><p className="mt-1 text-sm text-emerald-50/55">Questions submitted</p></div><div className="rounded-2xl border border-white/10 bg-white/[.035] p-6"><PencilLine className="size-5 text-emerald-300" /><p className="mt-5 text-3xl font-semibold text-white">{result.data?.answers.length ?? 0}</p><p className="mt-1 text-sm text-emerald-50/55">Answers shared</p></div><div className="rounded-2xl border border-white/10 bg-white/[.035] p-6"><Heart className="size-5 text-emerald-300" /><p className="mt-5 text-3xl font-semibold text-white">{result.data?.donations.length ?? 0}</p><p className="mt-1 text-sm text-emerald-50/55">Donation records</p></div></div><section className="mt-8 rounded-2xl border border-white/10 bg-white/[.035] p-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-emerald-300">Recent activity</p>{result.data?.timeline.length ? <div className="mt-5 divide-y divide-white/8">{result.data.timeline.map(item => <div key={item.id} className="flex items-start justify-between gap-5 py-4"><div><p className="font-medium text-white">{item.label}</p><p className="mt-1 text-xs uppercase tracking-[.12em] text-emerald-50/45">{item.contributionType}</p></div><p className="shrink-0 text-xs text-emerald-50/45">{new Date(item.createdAt).toLocaleDateString()}</p></div>)}</div> : <p className="mt-5 text-sm leading-6 text-emerald-50/55">Your future contributions will appear here after they are recorded.</p>}</section></QueryState></PublicPage>;
}
